### ISSUE TITLE
Import "template zbxDB DB2"  ( zbxdb_template_db2_v4.xml ) failed.

### ISSUE THREAD

**Issue by iv0001** [ikzelf/zbxdb#101]
Import "template zbxDB DB2"  ( zbxdb_template_db2_v4.xml ) failed.
The message is 
"Invalid parameter "/8/tags/2": value (tag, value)=(Application, LOG) already exists."

Zabbix Version: 6.0.12

**Comment by ikzelf** [comment]
You could try the generic version that currently is available for v5. I made the db2 variant ages ago during zabbix v4. Since the export xml files and the import changed they are not always easily importable.
What you can do is edit the file in a regular text editor and adjust it using an export from your current zabbix installation.
