### ISSUE TITLE
Zabbix Template Items Widget Graph Names Problem

### ISSUE THREAD

**Issue by seyacat** [ikzelf/zbxdb#14]
Zabbix 4.2

Graphics on Dashboard not suppor names with ","
All discovery items has ","

like this

p_ts[,SYSTEM,pctfreeMAX,timeleft1d]

**Comment by seyacat** [comment]
I modify template changin names with "," to "_"

Hope it helps and works fine

https://gist.github.com/seyacat/f5646dced27a14b6738787e63bf9b3bf

**Comment by ikzelf** [comment]
thanks.
For calculated items that will work OK. For trapper items the queries need to be changed to also generate the underscores, if needed.

**Comment by ikzelf** [comment]
Could that be caused by [https://support.zabbix.com/browse/ZBX-15149](url)? This zabbix bug is fixed ....

**Comment by ikzelf** [comment]
ah, the bug is 'fixed' by  documenting it instead of to solve the problem. It can be found just above [https://www.zabbix.com/documentation/4.2/manual/web_interface/frontend_sections/monitoring/dashboard/widgets#graph_classic](url)
There is not much I can do about it, other than what you already did.
