### ISSUE TITLE
How to configure oracle listener monitor

### ISSUE THREAD

**Issue by absz1980** [ikzelf/zbxdb#46]
How can I configure oracle listener monitor.
I add template zbx_tnslsnr attached but I don't see latest data.
Can you help, please?

**Comment by ikzelf** [comment]
If you read the template definitions, you can see that it only has a discovery rule. The discovery rule has item and trigger prototypes, that just need #DNSNAME and #PORT macros. In example_tools there is a zbx_discover_lsnr.py script that translates a csv to a zabbix discovery array. So, just make a list of the listeners you want to check and run zbx_discover_lsnr.py to upload that list to zabbix. The csv list has no headers, just a list of NAME:port

**Comment by ikzelf** [comment]
You might as well use csv-to-lld.py for this 'discovery' [https://github.com/ikzelf/csv-to-lld](url)

**Comment by absz1980** [comment]
Hi, Roland

I tried on zabbix server and 

[zbxdb@msk01-monapp02 zbxdb]$ /home/zbxdb/zbxdb/example_tools/zbx_discover_lsnr.py -c example_tools/hosts.csv -s sysmon.uralsibins.ru -p 10051  -H MSK01-AISDB02 -k oratns.lld
Traceback (most recent call last):
  File "/home/zbxdb/zbxdb/example_tools/zbx_discover_lsnr.py", line 37, in <module>
    dns, port = c.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
[zbxdb@msk01-monapp02 zbxdb]$ cat example_tools/hosts.csv
msk01-aisdb02.uralsibins.ru:1521


I don`t understand that I should to do with https://github.com/ikzelf/csv-to-lld

**Comment by ikzelf** [comment]
What is in hosts.csv ? Expected are 2 columns separated by ":".

Since zbx_discover_lsnr.py is nothing more than a converter that converts a delimited file to a valid json discovery array, I generalised that a bit in the form of csv-to-lld.py (this expects a header line with the column names. The discovery macros are generated from the column names)

**Comment by absz1980** [comment]
What do I doing?
What do I run csv-to-lld.py?

**Comment by ikzelf** [comment]
$>cat lsnr.csv
{DNSNAME};{PORT}
orahost1;1521
orahost2;1521

bin/csv-to-lld.py -c lsnr.csv -z MSK01-AISDB02 -l oratns.lld

**Comment by absz1980** [comment]
I ran on zabbix server

[zbxdb@msk01-monapp02 bin]$ ./csv-to-lld.py -c lsnr.csv -z MSK01-AISDB02 -l oratns.lld
zabbix_sender [2756]: DEBUG: answer [{"response":"success","info":"processed: 1; failed: 0; total: 1; seconds spent: 0.000235"}]
Response from "localhost:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000235"
sent: 1; skipped: 0; total: 1
[zbxdb@msk01-monapp02 bin]$ cat lsnr.csv
{DNSNAME};{PORT}
orahost1;1521
orahost2;1521

What`s next?

**Comment by ikzelf** [comment]
Now you should be able to see your listener items.
BTW: smartest is to [also] put them on a host that is not the database server. Doing so will also check eventual firewall's ....

**Comment by absz1980** [comment]
I`ve got it.

[zbxdb@msk01-monapp02 csv-to-lld]$ cat bin/lsnr.csv
{DNSNAME};{PORT}
MSK01-AISDB02:1521

[zbxdb@msk01-monapp02 csv-to-lld]$ cd bin
[zbxdb@msk01-monapp02 bin]$ ./csv-to-lld.py -c lsnr.csv -z MSK01-AISDB02 -l oratns.lld
zabbix_sender [97547]: DEBUG: answer [{"response":"success","info":"processed: 1; failed: 0; total: 1; seconds spent: 0.000094"}]
Response from "localhost:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000094"
sent: 1; skipped: 0; total: 1

And
![image](https://user-images.githubusercontent.com/11979643/87335678-5a826180-c549-11ea-885f-d02d8d714b5b.png)


How is it best practice?
Do I add one trigger on every dbhosts or add all on triggers on zabbix server host?

**Comment by ikzelf** [comment]
it depends.
The net.tcp checks are executed by the zabbix server or proxy. That's the reason I keep them defined there because it reminds me that the access is from a client. It is also easier to define them using the csv-to-lld.py script. Just one template on one location that handles all your listeners on all your hosts.
If you also want to know about the process state of the listener, you can create an item that checks just that, on the database server.

In a rac installation you will have multiple listeners .... if one of them is down, no problem. If all of them are down -> problem.

With even correlation you can prevent the generation of multiple events, if you want.
Think about what first your situation the best. As always, there are more ways to do it.

**Comment by absz1980** [comment]
Do I understand correctly?
Do I need link template zbx_tnslsnr on zabbix server or proxy only and add into csv file host:port all listeners and
run csv-to-lld.py -c lsnr.csv -z "zabbix-server" -l oratns.lld?

**Comment by ikzelf** [comment]
yes, that would make sense.
That is what I do in my installations.

**Comment by ikzelf** [comment]
Did you get this up and running?
Next to the simple service check there is also a performance script that should be implemented as userparameter on the agent.

**Comment by absz1980** [comment]
I get this up and running on Zabbix Server
What is the performance script? How can I implement it?

**Comment by ikzelf** [comment]
In example_tools/ you find tnslsnr-ping.py copy this to an agent script directory.
In the template there is an item prototype with "tnsping[{#DNSNAME},{#PORT}]" as key. Implement that as a user param in the agent like: "UserParameter = tnsping[*],/opt/zabbix/linux/lsnrping.py -s $1 -p $2" and restart the agent.

**Comment by ikzelf** [comment]
I assume this is working now.
