### ISSUE TITLE
autodiscovery failed on Postgresql 11

### ISSUE THREAD

**Issue by szelga** [ikzelf/zbxdb#7]
error message:

```
key=checks_60m.p_ts ZBXDB-42501: Db execution error: permission denied for tablespace pg_global
```

i've created user with following permissions:

```sql
CREATE USER zabbix WITH ENCRYPTED PASSWORD 'password';
GRANT CONNECT ON DATABASE postgres TO zabbix;
GRANT USAGE ON SCHEMA public TO zabbix;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO zabbix;
```

if i call `p_ts.lld` query manually, it returns correct data.

**Comment by ikzelf** [comment]
This is a privilege problem in the postgres database. This query tries to find  the sizing of the database and I could find no other way to run this than  to give the zabbix user a super user privilege. Not exactly what  I hoped for since I prefer read only privs ...... If you  have a better solution, please share ....

**Comment by szelga** [comment]
well, i guess, this is not a big problem in my case (to give a super user privilege). you might wanna update documentation then, as it states, that one should "use an account with the least required privileges".

**Comment by ikzelf** [comment]
yes, it already states what you said …. just, I can not help that postgres does not expose those internal tables to a regular SQL using user. But: I set the session to readonly.
Still, the user can read more than should …. Let’s hope postgres does evolve more so we can make it  more gdpr friendly.
